# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

- name: Cucumber Report to Annotations
  # You may pin to the exact commit or the version.
  # uses: deblockt/cucumber-report-annotations-action@af1f8e79707c16a5633a7b8c380c749fa2015fc4
  uses: deblockt/cucumber-report-annotations-action@v1.12
  with:
    # github token
    access-token: 
    # glob to cucumber json files
    path: # default is **/cucumber-report.json
    # the check status to use on cucumber error. Can be 'success', 'neutral' or 'failure'
    check-status-on-error: # default is failure
    # the check status to use on cucumber undefined steps. Can be 'success', 'neutral' or 'failure'
    check-status-on-undefined: # default is success
    # the check status to use on cucumber pending steps. Can be 'success', 'neutral' or 'failure'
    check-status-on-pending: # default is success
    # the annotation status on error. Can be 'notice', 'warning', 'failure'
    annotation-status-on-error: # optional, default is failure
    # the annotation status on undefined steps. Can be 'notice', 'warning', 'failure'. if this property is not set, no annotation will be generated for undefined steps
    annotation-status-on-undefined: # optional
    # the annotation status on pending steps. Can be 'notice', 'warning', 'failure'. if this property is not set, no annotation will be generated for pending steps
    annotation-status-on-pending: # optional
    # if it is set to true, the number of errors will be indicated on the check title (visible on the pr check)
    show-number-of-error-on-check-title: # optional, default is true
    # indicate the number of test in error to fail the build. If the value is -1 this action will never fail the build.
    number-of-test-error-to-fail-job: # optional, default is -1
    # the name of the check
    name: # optional, default is Cucumber report

    - name: Gherkin Linter
  # You may pin to the exact commit or the version.
  # uses: restqa/gherkin-linter-action@11429cfad9c5ec6a160083927353eb833ed3a5d0
  uses: restqa/gherkin-linter-action@0.0.1
  with:
    # Specify path to folder where the feature files are located
    path: # optional, default is .
    # Specify the Configuration file
    config_file: # optional, default is /root/.gherkin-lintrc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
